name: Convert Markdown to PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install Dependencies (Pandoc + basic LaTeX)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base

      - name: Convert Markdown to PDF
        run: |
          pandoc README.md -o README.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: README-pdf
          path: README.pdf
